

server:
  port: 5000
  context-path: /uaa
  use-forward-headers: false

security:
  basic:
    enabled: false

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


evolution:
  certificate:
    key: mySecretKey
  accessTokenValiditySeconds: 25000
  refreshTokenValiditySeconds: 300000
  default:
    defaultUserUsername: user_evolution@evolution.com
    defaultUserPassword: user_evolution@evolution.com